### ISSUE TITLE
ELIFECYCLE error

### ISSUE THREAD

**Issue by giac0m0** [jamesmorgan/devicecast#2]
I'm having an issue installing this using OSX 10.9.5

and have installed:
```
$ npm -v
5.3.0

$ node -v
v8.3.0
```
I've tried deleting the following folders:

```
$ rm -fr /Users/giacomo/.node-gyp
$ rm -fr /Users/giacomo/.npm
$ rm -fr node_modules
```
but the install commands throw up the same errors.  

```
npm install webcast-osx-audio -save
```

```
> osx-audio@0.2.0 install /Users/giacomo/Downloads/devicecast/node_modules/osx-audio
> node-gyp rebuild
```
```
20 errors generated.
make: *** [Release/obj.target/audio/src/bindings.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/giacomo/Downloads/devicecast/node_modules/osx-audio
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osx-audio@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osx-audio@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jamesmorgan** [comment]
Try install it using the version specified on the README - https://github.com/jamesmorgan/devicecast#development

I know I had issues originally when using newer versions of node so there may be issues with older ones as well. One of the libraries is bound to a specific version unfortunately, I will check if the its been fixed. Closing for now

**Comment by giac0m0** [comment]
Thanks - I did start with the version of node in the readme, but NPM is b0rked:

```
$ npm -v

/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by giac0m0** [comment]
... and I realise now that clearing all versions of npm and doing a fresh install of v0.10.38 resolved the issue.
