### ISSUE TITLE
webcast-osx-audio bindings error

### ISSUE THREAD

**Issue by giac0m0** [jamesmorgan/devicecast#4]
```
$ npm start

> devicecast@0.2.0 start /Users/giacomo/Downloads/devicecast
> electron .

Logger level set to debug
2017-08-16T12:56:44.425Z - debug: Adding Scanning for Devices...
2017-08-16T12:56:44.429Z - debug: Adding cast to device menu
2017-08-16T12:56:44.431Z - debug: Attempting to start stream using exec
2017-08-16T12:56:44.453Z - debug: Adding About Stream Feature Item
2017-08-16T12:56:44.454Z - debug: Adding stream menu
2017-08-16T12:56:44.456Z - debug: Adding About Menu Item
2017-08-16T12:56:44.457Z - debug: Adding Quit Menu Item
2017-08-16T12:56:44.469Z - error: uncaughtException: bind EADDRINUSE 0.0.0.0:3333 date=Wed Aug 16 2017 13:56:44 GMT+0100 (BST), pid=6406, uid=501, gid=20, cwd=/Users/giacomo/Downloads/devicecast, execPath=/Users/giacomo/Downloads/devicecast/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, version=v5.1.1, argv=[/Users/giacomo/Downloads/devicecast/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, .], rss=67325952, heapTotal=35368512, heapUsed=24728120, loadavg=[1.1748046875, 1.71630859375, 2.14990234375], uptime=3264, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=856, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=879, method=_exceptionWithHostPort, native=false, column=18, file=dgram.js, function=null, line=213, method=null, native=false, column=9, file=node.js, function=doNTCallback3, line=476, method=null, native=false, column=17, file=node.js, function=process._tickCallback, line=382, method=_tickCallback, native=false], stack=[Error: bind EADDRINUSE 0.0.0.0:3333,     at Object.exports._errnoException (util.js:856:11),     at exports._exceptionWithHostPort (util.js:879:20),     at dgram.js:213:18,     at doNTCallback3 (node.js:476:9),     at process._tickCallback (node.js:382:17)]
2017-08-16T12:56:44.489Z - error: uncaughtException: bind EADDRINUSE 0.0.0.0:3334 date=Wed Aug 16 2017 13:56:44 GMT+0100 (BST), pid=6406, uid=501, gid=20, cwd=/Users/giacomo/Downloads/devicecast, execPath=/Users/giacomo/Downloads/devicecast/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, version=v5.1.1, argv=[/Users/giacomo/Downloads/devicecast/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, .], rss=67715072, heapTotal=35368512, heapUsed=25031760, loadavg=[1.1748046875, 1.71630859375, 2.14990234375], uptime=3264, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=856, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=879, method=_exceptionWithHostPort, native=false, column=18, file=dgram.js, function=null, line=213, method=null, native=false, column=9, file=node.js, function=doNTCallback3, line=476, method=null, native=false, column=17, file=node.js, function=process._tickCallback, line=382, method=_tickCallback, native=false], stack=[Error: bind EADDRINUSE 0.0.0.0:3334,     at Object.exports._errnoException (util.js:856:11),     at exports._exceptionWithHostPort (util.js:879:20),     at dgram.js:213:18,     at doNTCallback3 (node.js:476:9),     at process._tickCallback (node.js:382:17)]
2017-08-16T12:56:44.789Z - error: webcast-audio error

2017-08-16T12:56:44.790Z - info: Streaming process died

2017-08-16T12:56:46.665Z - error: webcast-audio error /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/node_modules/bindings/bindings.js:96
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/out/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/out/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/default/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/compiled/0.10.38/darwin/x64/bindings.node
    at bindings (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/lib/decoder.js:7:15)
    at Module._compile (module.js:456:26)

2017-08-16T12:56:46.666Z - info: Streaming process died /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/node_modules/bindings/bindings.js:96
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/out/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/Debug/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/out/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/Release/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/build/default/bindings.node
 â /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/compiled/0.10.38/darwin/x64/bindings.node
    at bindings (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame/lib/decoder.js:7:15)
    at Module._compile (module.js:456:26)

2017-08-16T12:57:02.042Z - error: child process exited with code 8
```

**Comment by giac0m0** [comment]
Seems to have resolved this with a fresh npm install of webcast-osx-audio:

```
$ npm install webcast-osx-audio

> osx-audio@0.2.0 install /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/osx-audio
> node-gyp rebuild

  CXX(target) Release/obj.target/audio/src/bindings.o
  SOLINK_MODULE(target) Release/audio.node
  SOLINK_MODULE(target) Release/audio.node: Finished
\
> lame@1.2.4 install /Users/giacomo/Downloads/devicecast/node_modules/webcast-osx-audio/node_modules/lame
> node-gyp rebuild

deps/mpg123/test.target.mk:147: warning: overriding commands for target `Release/test'
deps/lame/test.target.mk:155: warning: ignoring old commands for target `Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable 'rsv' [-Wunused-variable]
    RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                               ^
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable 'cfg' [-Wunused-variable]
    SessionConfig_t const *const cfg = &gfc->cfg;
                                 ^
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable 'rov' [-Wunused-variable]
    RpgResult_t *const rov = &gfc->ov_rpg;
                       ^
3 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  LIBTOOL-STATIC Release/libmp3lame.a
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c:184:27: warning: comparison of integers of different signs: 'off_t' (aka 'long long') and 'unsigned long'
      [-Wsign-compare]
                                                if(fr->track_frames > TRACK_MAX_FRAMES) fr->track_frames = 0; /* endless stream? */
                                                   ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison of integers of different signs: 'unsigned long' and 'int' [-Wsign-compare]
        if(2*2*0x110*sizeof(real) > buffssize)
           ~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison of integers of different signs: 'ssize_t' (aka 'long') and 'unsigned long'
      [-Wsign-compare]
                        if(got < sizeof(readbuf)) /* That naturally catches got == 0, too. */
                           ~~~ ^ ~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char*))
                           ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c:804:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:818:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:842:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:890:4: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1021:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1036:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1059:6: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1088:4: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro 'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
8 warnings generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_real.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  LIBTOOL-STATIC Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  LIBTOOL-STATIC Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
  CXX(target) Release/obj.target/bindings/src/node_lame.o
  CXX(target) Release/obj.target/bindings/src/node_mpg123.o
  SOLINK_MODULE(target) Release/bindings.node
  SOLINK_MODULE(target) Release/bindings.node: Finished
webcast-osx-audio@0.1.4 node_modules/webcast-osx-audio
âââ minimist@1.2.0
âââ debug@2.6.8 (ms@2.0.0)
âââ chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
âââ express@4.15.4 (setprototypeof@1.0.3, escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.6, merge-descriptors@1.0.1, methods@1.1.2, path-to-regexp@0.1.7, encodeurl@1.0.1, range-parser@1.2.0, parseurl@1.3.1, fresh@0.5.0, vary@1.1.1, content-type@1.0.2, etag@1.8.0, statuses@1.3.1, cookie@0.3.1, content-disposition@0.5.2, serve-static@1.12.4, depd@1.1.1, qs@6.5.0, on-finished@2.3.0, finalhandler@1.0.4, proxy-addr@1.1.5, send@0.15.4, accepts@1.3.3, type-is@1.6.15)
âââ osx-audio@0.2.0 (bindings@1.3.0)
âââ lame@1.2.4 (bindings@1.3.0, nan@2.6.2, readable-stream@1.1.14)
```
```
ShinyPro:devicecast giacomo$ npm start

> devicecast@0.2.0 start /Users/giacomo/Downloads/devicecast
> electron .

Logger level set to debug
2017-08-16T13:03:01.852Z - debug: Adding Scanning for Devices...
2017-08-16T13:03:01.858Z - debug: Adding cast to device menu
2017-08-16T13:03:01.859Z - debug: Attempting to start stream using exec
2017-08-16T13:03:01.885Z - debug: Adding About Stream Feature Item
2017-08-16T13:03:01.890Z - debug: Adding stream menu
2017-08-16T13:03:01.892Z - debug: Adding About Menu Item
2017-08-16T13:03:01.893Z - debug: Adding Quit Menu Item
2017-08-16T13:03:02.452Z - info: webcast-audio stream launched streaming at http://192.168.1.103:3000/stream.mp3

2017-08-16T13:03:04.345Z - info: Found Device [Living room Home]
2017-08-16T13:03:12.931Z - debug: TODO - Refresh Items
2017-08-16T13:04:33.162Z - debug: TODO - Refresh Items
2017-08-16T13:04:39.158Z - info: Found Device [Jongo S3 02]
2017-08-16T13:04:39.212Z - debug: Adding Jongo Menu Item [Jongo S3 02]
2017-08-16T13:04:42.977Z - info: Attempting to play to Jongo device Jongo S3 02
2017-08-16T13:04:42.978Z - info: Switching Audio source output=Soundflower (2ch), input=Soundflower (2ch)
2017-08-16T13:04:43.026Z - info: Calling load() on device [Jongo S3 02 - 192.168.1.108]
BoomDevice
Soundflower (2ch)
2017-08-16T13:04:44.112Z - debug: status InstanceID=0, TransportPlaySpeed=1, RecordStorageMedium=NOT_IMPLEMENTED, CurrentPlayMode=NORMAL, TransportState=STOPPED, RecordMediumWriteStatus=NOT_IMPLEMENTED, CurrentRecordQualityMode=NOT_IMPLEMENTED, SyncOffset=P00:00:00.000, CurrentTrackURI=, PlaybackStorageMedium=NOT_IMPLEMENTED, NumberOfTracks=0, CurrentMediaDuration=0:00:00, NextAVTransportURIMetaData=, AVTransportURI=, PossiblePlaybackStorageMedia=None,Network, PossibleRecordStorageMedia=NOT_IMPLEMENTED, NextAVTransportURI=, TransportStatus=OK, CurrentTrackMetaData=, AVTransportURIMetaData=, CurrentTrackDuration=0:00:00, PossibleRecordQualityMode=NOT_IMPLEMENTED, CurrentTrack=0
2017-08-16T13:04:44.400Z - debug: playing ...
2017-08-16T13:04:44.401Z - debug: Removing menu label to [Refresh Devices...]
2017-08-16T13:04:44.402Z - debug: Removing menu label to []
2017-08-16T13:04:44.402Z - debug: Setting menu label to [Jongo S3 02 ð]
2017-08-16T13:06:44.136Z - debug: status InstanceID=0, CurrentTrackURI=http://192.168.1.103:3000/stream.mp3, NumberOfTracks=1, AVTransportURI=http://192.168.1.103:3000/stream.mp3, CurrentTrackMetaData=<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sec="http://www.sec.co.kr/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><item id="0" parentID="-1" restricted="false"><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:title>Streaming Mac OSX</dc:title><dc:creator>DeviceCast</dc:creator></item></DIDL-Lite>, AVTransportURIMetaData=<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sec="http://www.sec.co.kr/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><item id="0" parentID="-1" restricted="false"><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:title>Streaming Mac OSX</dc:title><dc:creator>DeviceCast</dc:creator></item></DIDL-Lite>, CurrentTrack=1
2017-08-16T13:08:44.175Z - debug: status InstanceID=0, TransportState=TRANSITIONING
2017-08-16T13:08:44.175Z - debug: loading
2017-08-16T13:10:44.238Z - debug: status InstanceID=0, TransportState=PLAYING
2017-08-16T13:10:44.238Z - debug: playing
2017-08-16T13:10:45.328Z - debug: position 0
2017-08-16T13:10:45.564Z - debug: duration 0
```
